// frontend-nextjs/app/page.tsx
"use client";
import { useState } from "react";

export default function Home() {
  const [phone, setPhone] = useState("");
  const [otp, setOtp] = useState("");

  const login = async () => {
    const res = await fetch("http://localhost:5272/auth/login/next", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include", // importante para la cookie
      body: JSON.stringify({ phone, otp }),
    });
    if (!res.ok) { alert("Invalid OTP"); return; }
    alert("Logged in!");
  };

  const resume = () => {
    window.location.href = "http://localhost:4200/"; // Angular User App
  };

  return (
    <main style={{ padding: 24 }}>
      <h1>Next Hub</h1>
      <div style={{ display:"grid", gap:12, maxWidth:360 }}>
        <input placeholder="Phone" value={phone} onChange={e=>setPhone(e.target.value)} />
        <input placeholder="OTP (use 123456)" value={otp} onChange={e=>setOtp(e.target.value)} />
        <button onClick={login}>Login</button>
        <button onClick={resume}>Resume Application → Angular1</button>
      </div>
    </main>
  );
}

// frontend-angular2/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  private http = inject(HttpClient);

  email = 'admin@demo.com';
  password = 'admin123';
  logged = false;

  login(e: Event) {
    e.preventDefault();
    this.http.post('http://localhost:5272/auth/login/admin',
      { email: this.email, password: this.password }
    ).subscribe({
      next: () => this.logged = true,
      error: () => alert('Invalid admin credentials')
    });
  }

  openUser(adminName: string) {
    window.location.href = `http://localhost:4200/?adminName=${encodeURIComponent(adminName)}`;
  }
}

<div style="padding:24px">
  <h1>Angular Admin App</h1>

  <form (submit)="login($event)" *ngIf="!logged" style="display:grid; gap:12px; max-width:320px">
    <input placeholder="Email" [(ngModel)]="email" name="email" />
    <input placeholder="Password" [(ngModel)]="password" name="password" type="password" />
    <button>Login</button>
  </form>

  <div *ngIf="logged">
    <h3>Applications</h3>
    <ul>
      <li><button (click)="openUser('Alice Admin')">Open First Application</button></li>
    </ul>
  </div>
</div>
